---

apiVersion: v1
kind: Service
metadata:
  name: sistema-matricula-stable
  namespace: sistema-matricula-prod
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: sistema-matricula
    env: prod

---

apiVersion: v1
kind: Service
metadata:
  name: sistema-matricula-canary
  namespace: sistema-matricula-prod
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: sistema-matricula
    env: prod

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sistema-matricula-ingress
  namespace: sistema-matricula-prod
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: sistema-matricula.exemplo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sistema-matricula-stable
            port:
              number: 80