---
# Service ACTIVE - Recebe tráfego de produção
apiVersion: v1
kind: Service
metadata:
  name: sistema-matricula-active
  namespace: sistema-matricula-dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: sistema-matricula
    env: dev

---
# Service PREVIEW - Para testar nova versão
apiVersion: v1
kind: Service
metadata:
  name: sistema-matricula-preview
  namespace: sistema-matricula-dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: sistema-matricula
    env: dev

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sistema-matricula-ingress
  namespace: sistema-matricula-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: sistema-matricula-dev.exemplo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sistema-matricula-active
            port:
              number: 80